version: "3.8"
services:
  app:
    build: ./.devcontainer
    volumes:
      - .:/workspace/heard-takehome:cached
    ports:
      - "5173:5173"
      - "3001:3001"
    command: sh -c "npm --prefix backend run dev & npm --prefix frontend run dev"
    